### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by gowrijsuria** [NVlabs/imaginaire#119]
Hi @mingyuliutw, 

I was trying to set up the conda environment and install packages with the following code given in INSTALL.md.

```conda env create --file scripts/requirements_conda.yaml
# install third-party libraries
export CUDA_VERSION=$(nvcc --version| grep -Po "(\d+\.)+\d+" | head -1)
CURRENT=$(pwd)
for p in correlation channelnorm resample2d bias_act upfirdn2d; do
    cd imaginaire/third_party/${p};
    rm -rf build dist *info;
    python setup.py install;
    cd ${CURRENT};
done
```

I got the following error. (Note: I'm using cuda 10.1).

```No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-10.1'
CUDA_VERSION: 10.1
running install
running bdist_egg
running egg_info
creating correlation_cuda.egg-info
writing correlation_cuda.egg-info/PKG-INFO
writing dependency_links to correlation_cuda.egg-info/dependency_links.txt
writing top-level names to correlation_cuda.egg-info/top_level.txt
writing manifest file 'correlation_cuda.egg-info/SOURCES.txt'
reading manifest file 'correlation_cuda.egg-info/SOURCES.txt'
writing manifest file 'correlation_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.9
copying correlation.py -> build/lib.linux-x86_64-3.9
running build_ext
Traceback (most recent call last):
  File "/home/gowri.lekshmy/imaginaire/imaginaire/third_party/correlation/setup.py", line 31, in <module>
    setup(name='correlation_cuda',py_modules=['correlation'],ext_modules=[CUDAExtension('correlation_cuda', ['./src/correlation_cuda.cc','./src/correlation_cuda_kernel.cu'], extra_compile_args={'cxx': ['-Wall', '-std=c++14'],'nvcc': nvcc_args})],cmdclass={'build_ext': BuildExtension})
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
    self._check_cuda_version()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 777, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 56, in parse
    return Version(version)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-10.1'
CUDA_VERSION: 10.1
running install
running bdist_egg
running egg_info
creating channelnorm_cuda.egg-info
writing channelnorm_cuda.egg-info/PKG-INFO
writing dependency_links to channelnorm_cuda.egg-info/dependency_links.txt
writing top-level names to channelnorm_cuda.egg-info/top_level.txt
writing manifest file 'channelnorm_cuda.egg-info/SOURCES.txt'
reading manifest file 'channelnorm_cuda.egg-info/SOURCES.txt'
writing manifest file 'channelnorm_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.9
copying channelnorm.py -> build/lib.linux-x86_64-3.9
running build_ext
Traceback (most recent call last):
  File "/home/gowri.lekshmy/imaginaire/imaginaire/third_party/channelnorm/setup.py", line 31, in <module>
    setup(
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
    self._check_cuda_version()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 777, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 56, in parse
    return Version(version)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-10.1'
CUDA_VERSION: 10.1
running install
running bdist_egg
running egg_info
creating resample2d_cuda.egg-info
writing resample2d_cuda.egg-info/PKG-INFO
writing dependency_links to resample2d_cuda.egg-info/dependency_links.txt
writing top-level names to resample2d_cuda.egg-info/top_level.txt
writing manifest file 'resample2d_cuda.egg-info/SOURCES.txt'
reading manifest file 'resample2d_cuda.egg-info/SOURCES.txt'
writing manifest file 'resample2d_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.9
copying resample2d.py -> build/lib.linux-x86_64-3.9
running build_ext
Traceback (most recent call last):
  File "/home/gowri.lekshmy/imaginaire/imaginaire/third_party/resample2d/setup.py", line 31, in <module>
    setup(
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
    self._check_cuda_version()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 777, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 56, in parse
    return Version(version)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-10.1'
CUDA_VERSION: 10.1
running install
running bdist_egg
running egg_info
creating bias_act_cuda.egg-info
writing bias_act_cuda.egg-info/PKG-INFO
writing dependency_links to bias_act_cuda.egg-info/dependency_links.txt
writing top-level names to bias_act_cuda.egg-info/top_level.txt
writing manifest file 'bias_act_cuda.egg-info/SOURCES.txt'
reading manifest file 'bias_act_cuda.egg-info/SOURCES.txt'
writing manifest file 'bias_act_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.9
copying bias_act.py -> build/lib.linux-x86_64-3.9
running build_ext
Traceback (most recent call last):
  File "/home/gowri.lekshmy/imaginaire/imaginaire/third_party/bias_act/setup.py", line 31, in <module>
    setup(
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
    self._check_cuda_version()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 777, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 56, in parse
    return Version(version)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-10.1'
CUDA_VERSION: 10.1
running install
running bdist_egg
running egg_info
creating upfirdn2d_cuda.egg-info
writing upfirdn2d_cuda.egg-info/PKG-INFO
writing dependency_links to upfirdn2d_cuda.egg-info/dependency_links.txt
writing top-level names to upfirdn2d_cuda.egg-info/top_level.txt
writing manifest file 'upfirdn2d_cuda.egg-info/SOURCES.txt'
reading manifest file 'upfirdn2d_cuda.egg-info/SOURCES.txt'
writing manifest file 'upfirdn2d_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.9
copying upfirdn2d.py -> build/lib.linux-x86_64-3.9
running build_ext
Traceback (most recent call last):
  File "/home/gowri.lekshmy/imaginaire/imaginaire/third_party/upfirdn2d/setup.py", line 31, in <module>
    setup(
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
    self._check_cuda_version()
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 777, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 56, in parse
    return Version(version)
  File "/home/gowri.lekshmy/anaconda3/envs/imaginaire/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

The issue is in this line.
```
setup(name='correlation_cuda',py_modules=['correlation'],ext_modules=[CUDAExtension('correlation_cuda', ['./src/correlation_cuda.cc','./src/correlation_cuda_kernel.cu'], extra_compile_args={'cxx': ['-Wall', '-std=c++14'],'nvcc': nvcc_args})],cmdclass={'build_ext': BuildExtension})
```

Kindly help me resolve this issue.
Thanks

**Comment by SYLin117** [comment]
@gowrijsuria Hi, did you find a way to fix this problem? I'm facing a similar situation now.

**Comment by digvijayad** [comment]
@gowrijsuria @SYLin117  Did you solve this issue ?

**Comment by gowrijsuria** [comment]
Hi @SYLin117 @digvijayad, no I couldn't resolve the issue. I used their older GitHub repo instead.
