### ISSUE TITLE
pynvml.nvml.NVMLError_Unknown

### ISSUE THREAD

**Issue by fantasyfw** [NVlabs/imaginaire#161]
I met the following error when running inference, don't know how to fix it.
```
Traceback (most recent call last):
  File "inference.py", line 95, in <module>
    main()
  File "inference.py", line 40, in main
    set_affinity(args.local_rank)
  File "/mnt/c/Users/wongm/Desktop/Neural_Actor_Main_Code/imaginaire/imaginaire/utils/gpu_affinity.py", line 56, in set_affinity
    os.sched_setaffinity(0, dev.getCpuAffinity())
  File "/mnt/c/Users/wongm/Desktop/Neural_Actor_Main_Code/imaginaire/imaginaire/utils/gpu_affinity.py", line 37, in getCpuAffinity
    for j in pynvml.nvmlDeviceGetCpuAffinity(self.handle, device._nvml_affinity_elements):
  File "/home/finn/.local/lib/python3.6/site-packages/pynvml/nvml.py", line 1745, in nvmlDeviceGetCpuAffinity
    _nvmlCheckReturn(ret)
  File "/home/finn/.local/lib/python3.6/site-packages/pynvml/nvml.py", line 765, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.nvml.NVMLError_Unknown: Unknown Error
```

**Comment by fantasyfw** [comment]
Fixed

**Comment by Ethan-agrs** [comment]
Could you teach me how to fix that error?
