### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443):

### ISSUE THREAD

**Issue by fz5400** [NVlabs/imaginaire#177]
(imaginaire) root@a4f1b3824961:/mnt/data/_tt_/imaginaire# python inference.py --single_gpu --num_workers 0 --config configs/projects/fs_vid2vid/face_forensics/ampO1.yaml --output_dir projects/fs_vid2vid/output/face_forensics
Using random seed 0
cudnn benchmark: True
cudnn deterministic: False
Creating metadata
['images', 'landmarks-dlib68']
Data file extensions: {'images': 'jpg', 'landmarks-dlib68': 'json'}
Searching in dir: images
Found 1 sequences
Found 1 files
['images', 'landmarks-dlib68']
Data file extensions: {'images': 'jpg', 'landmarks-dlib68': 'json'}
Searching in dir: images
Found 1 sequences
Found 30 files
Folder at projects/fs_vid2vid/test_data/faceForensics/reference/images opened.
Folder at projects/fs_vid2vid/test_data/faceForensics/reference/landmarks-dlib68 opened.
Folder at projects/fs_vid2vid/test_data/faceForensics/driving/images opened.
Folder at projects/fs_vid2vid/test_data/faceForensics/driving/landmarks-dlib68 opened.
Num datasets: 2
Num sequences: 2
Max sequence length: 30
Epoch length: 1
Using random seed 0
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True for input.
        Num. of channels in the input image: 3
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True for input.
Concatenate landmarks-dlib68:
    ext: json
    num_channels: 1
    interpolator: None
    normalize: False
    pre_aug_ops: decode_json
    post_aug_ops: vis::imaginaire.utils.visualization.face::connect_face_keypoints for input.
        Num. of channels in the input label: 1
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True for input.
        Num. of channels in the input image: 3
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True for input.
        Num. of channels in the input image: 3
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True for input.
        Num. of channels in the input image: 3
Initialized temporal embedding network with the reference one.
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True for input.
Concatenate landmarks-dlib68:
    ext: json
    num_channels: 1
    interpolator: None
    normalize: False
    pre_aug_ops: decode_json
    post_aug_ops: vis::imaginaire.utils.visualization.face::connect_face_keypoints for input.
        Num. of channels in the input label: 1
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True for input.
        Num. of channels in the input image: 3
Initialize net_G and net_D weights using type: xavier gain: 0.02
Using random seed 0
net_G parameter count: 91,145,502
net_D parameter count: 5,593,922
Use custom initialization for the generator.
Setup trainer.
Using automatic mixed precision training.
Augmentation policy: 
GAN mode: hinge
/root/anaconda3/envs/imaginaire/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and may be removed in the future, "
/root/anaconda3/envs/imaginaire/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG19_Weights.IMAGENET1K_V1`. You can also use `weights=VGG19_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Perceptual loss:
        Mode: vgg19
Downloading 1hF8vS6YeHkx3j2pfCeQqqZGwA_PJq_Da
Traceback (most recent call last):
  File "/root/anaconda3/envs/imaginaire/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/root/anaconda3/envs/imaginaire/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/root/anaconda3/envs/imaginaire/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/imaginaire/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/root/anaconda3/envs/imaginaire/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/root/anaconda3/envs/imaginaire/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/root/anaconda3/envs/imaginaire/lib/python3.7/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/root/anaconda3/envs/imaginaire/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f536f929950>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/imaginaire/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/root/anaconda3/envs/imaginaire/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/root/anaconda3/envs/imaginaire/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1hF8vS6YeHkx3j2pfCeQqqZGwA_PJq_Da (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f536f929950>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference.py", line 99, in <module>
  File "inference.py", line 74, in main
    
  File "/mnt/data/_tt_/imaginaire/imaginaire/utils/trainer.py", line 62, in get_trainer
    train_data_loader, val_data_loader)
  File "/mnt/data/_tt_/imaginaire/imaginaire/trainers/fs_vid2vid.py", line 43, in __init__
    train_data_loader, val_data_loader)
  File "/mnt/data/_tt_/imaginaire/imaginaire/trainers/vid2vid.py", line 46, in __init__
    train_data_loader, val_data_loader)
  File "/mnt/data/_tt_/imaginaire/imaginaire/trainers/base.py", line 99, in __init__
    self._init_loss(cfg)
  File "/mnt/data/_tt_/imaginaire/imaginaire/trainers/vid2vid.py", line 145, in _init_loss
    self.criteria['Flow'] = FlowLoss(cfg)
  File "/mnt/data/_tt_/imaginaire/imaginaire/losses/flow.py", line 59, in __init__
    self.flowNet = flow_module.FlowNet(pretrained=True)
  File "/mnt/data/_tt_/imaginaire/imaginaire/third_party/flow_net/flow_net.py", line 29, in __init__
    '1hF8vS6YeHkx3j2pfCeQqqZGwA_PJq_Da')
  File "/mnt/data/_tt_/imaginaire/imaginaire/utils/io.py", line 133, in get_checkpoint
    download_file(url, full_checkpoint_path)
  File "/mnt/data/_tt_/imaginaire/imaginaire/utils/io.py", line 72, in download_file
    response = session.get(URL, stream=True)
  File "/root/anaconda3/envs/imaginaire/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/root/anaconda3/envs/imaginaire/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/anaconda3/envs/imaginaire/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/root/anaconda3/envs/imaginaire/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1hF8vS6YeHkx3j2pfCeQqqZGwA_PJq_Da (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f536f929950>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by fz5400** [comment]
problem solved，
find` ./imaginaire/utils/io.py` file 
add the code `print(full_checkpoint_path)` after line 130, then the save path will be showed, download the model manually and put it under the save dir
