### ISSUE TITLE
Google colab notebooks, anyone?

### ISSUE THREAD

**Issue by terekita** [NVlabs/imaginaire#25]
Hello, Has anyone gotten this working with Google Colab yet? Would be very excited to check it out!! I'm working on it, but haven't had success yet.

One major issue:  Colab is running cuda 10.1, and it looks like it may not be possible to do a local installation of cuda 10.2, which is needed for Imaginaire to work.

**Comment by fernando12170209** [comment]
Me too, I hope run this magic library in colab soon

**Comment by seawee1** [comment]
Hi, I did it! The trick is to just use PyTorch Cuda 10.1 version. My first COCO-FUNIT model is training in Colab right now, so Cuda 10.2 doesn't seem to be a hard requirement for imaginaire to work.

Link to my Colab notebook:
[https://colab.research.google.com/drive/1OM7zB8EmDpqIl7zRELzHej7Xh4Swcvat?usp=sharing](Colab Notebook)

**Comment by terekita** [comment]
@seawee1 , I apologize for missing the notification of your reply, and thank you very much for sharing the notebook! Were you able to train models on colab? 

When I try to train the MUNIT example, running 
`!python -m torch.distributed.launch --nproc_per_node=1 train.py \
--config configs/projects/munit/afhq_dog2cat/ampO1.yaml`
I get a memory allocation error, even using a High-RAM session...

**Comment by Sentero-esp12** [comment]
I'm getting the following error when running `!cd imaginaire && bash scripts/install.sh` on Colab: 
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-9ya9mu5f/setup.py", line 171, in <module>
        check_cuda_torch_binary_vs_bare_metal(torch.utils.cpp_extension.CUDA_HOME)
      File "/tmp/pip-req-build-9ya9mu5f/setup.py", line 102, in check_cuda_torch_binary_vs_bare_metal
        raise RuntimeError("Cuda extensions are being compiled with a version of Cuda that does " +
    RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 10.1.
    In some cases, a minor-version mismatch will not cause later errors:  https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check (at your own risk).
    Running setup.py install for apex ... error
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-9ya9mu5f/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-9ya9mu5f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-p7aeu7ws/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/apex Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 838, in install
    success = install_legacy(
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 397, in run
    installed = install_given_reqs(
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 82, in install_given_reqs
    requirement.install(
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 856, in install
    six.reraise(*exc.parent)
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 74, in install
    runner(
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 273, in runner
    call_subprocess(
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-9ya9mu5f/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-9ya9mu5f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-p7aeu7ws/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/apex Check the logs for full command output.
```

And when I run 
`!python inference.py --single_gpu --num_workers 0 \
--config configs/projects/fs_vid2vid/faceForensics/ampO1.yaml \
--output_dir projects/fs_vid2vid/output/faceForensics` I get:
```
Traceback (most recent call last):
  File "inference.py", line 13, in <module>
    from imaginaire.utils.logging import init_logging
  File "/content/imaginaire/imaginaire/utils/logging.py", line 10, in <module>
    from imaginaire.utils.meters import set_summary_writer
  File "/content/imaginaire/imaginaire/utils/meters.py", line 11, in <module>
    from apex import amp
ModuleNotFoundError: No module named 'apex'
```

I also tried changing Python version to 3.8.5
I would appreciate any help!

**Comment by krivimp4** [comment]
Hi all.

I am also getting an error message when trying to install imaginaire on colab. Pasting the last few lines below:

```
Successfully installed av-8.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
/usr/local/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "/content/imaginaire/train.py", line 11, in <module>
    import wandb
ModuleNotFoundError: No module named 'wandb'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 9567) of binary: /usr/local/bin/python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/usr/local/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-02-01_12:22:19
  host      : f64537d9895f
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 9567)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
 python -m torch.distributed.launch --nproc_per_node=1 train.py  --config configs/unit_test/spade.yaml >> /tmp/unit_test.log  [Failure] 
```
 
 Any clues?

**Comment by val-andreev** [comment]
Why hello there Krivi, fancy meeting you here! ¯\_(๑❛ᴗ❛๑)_/¯

Encountered the same issue as you and resolved it by installing wandb by:

pip install wandb---> for the colab env be sure to include an exclamationmark thus typing: !pip install wandb

Hope this helps!
Cheers!

Valio
