### ISSUE TITLE
Google Colab Installation Problem

### ISSUE THREAD

**Issue by kumar-neelabh** [NVlabs/imaginaire#49]
I'm trying to install Imaginaire on Google Colab (full installation log attached). Here's the error that I get on running the test_training.sh script:

100% 1/1 [00:00<00:00, 1736.77it/s]
100% 1/1 [00:00<00:00, 400.91it/s]
100% 1/1 [00:00<00:00, 1413.65it/s]
100% 1/1 [00:00<00:00, 1112.25it/s]
100% 1/1 [00:00<00:00, 1455.34it/s]
100% 1/1 [00:00<00:00, 945.30it/s]
 **python scripts/build_lmdb.py --config configs/unit_test/spade.yaml --paired --data_root dataset/unit_test/raw/spade/ --output_root dataset/unit_test/lmdb/spade --overwrite >> /tmp/unit_test.log  [Success]** 
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    from imaginaire.utils.gpu_affinity import set_affinity
  File "/content/gdrive/My Drive/audiovisual-compression/imaginaire/imaginaire/utils/gpu_affinity.py", line 9, in <module>
    pynvml.nvmlInit()
  File "/usr/local/lib/python3.6/dist-packages/pynvml/nvml.py", line 749, in nvmlInit
    check_return(ret)
  File "/usr/local/lib/python3.6/dist-packages/pynvml/nvml.py", line 366, in check_return
    raise NVMLError(ret)
pynvml.nvml.NVMLError_DriverNotLoaded: Driver Not Loaded
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'train.py', '--local_rank=0', '--config', 'configs/unit_test/spade.yaml']' returned non-zero exit status 1.
 **python -m torch.distributed.launch --nproc_per_node=1 train.py  --config configs/unit_test/spade.yaml >> /tmp/unit_test.log  [Failure]** 
[installation log.txt](https://github.com/NVlabs/imaginaire/files/5835745/installation.log.txt)

**Comment by arunmallya** [comment]
Sorry, might be some issue with the CUDA/driver versions on colab.

**Comment by arunmallya** [comment]
You can try to remove all calls to this file: https://github.com/NVlabs/imaginaire/blob/master/imaginaire/utils/gpu_affinity.py
This is the only one that uses `pynvml`

**Comment by seawee1** [comment]
See: #25
If nothing major changed the Colab notebook I provided there should work.

**Comment by krivimp4** [comment]
> See: #25 If nothing major changed the Colab notebook I provided there should work.

It doesn't, though. I've been trying to install it and I get the same error as kumarneelabh13
