### ISSUE TITLE
Inference for fewshotvid2vid? 

### ISSUE THREAD

**Issue by alessiapacca** [NVlabs/imaginaire#53]
So I wanted to try an inference on my own inputs, therefore I followed the instructions on the readme, I modified the faceForensic config with the correct path, but when I try to run it I get the following error:
```
Epoch length: 0
Traceback (most recent call last):
  File "inference.py", line 91, in <module>
    main()
  File "inference.py", line 87, in main
    trainer.test(test_data_loader, args.output_dir, cfg.inference_args)
  File "/content/drive/My Drive/imaginaire/imaginaire/trainers/fs_vid2vid.py", line 148, in test
    test_data_loader.dataset.set_inference_sequence_idx(
  File "/content/drive/My Drive/imaginaire/imaginaire/datasets/paired_few_shot_videos.py", line 46, in set_inference_sequence_idx
    assert index < len(self.mapping)
AssertionError
```

Any idea why?

**Comment by arunmallya** [comment]
Seems like there's an issue in the way you constructed the eval dataset. Did you create the LMDB using the `--paired` flag?
