### ISSUE TITLE
RuntimeError: apex.optimizers.FusedAdam requires cuda extensions

### ISSUE THREAD

**Issue by simon-eda** [NVlabs/imaginaire#62]
Dear All, 
i face an issue on windows 10 anaconda powershell, when running following command:

python inference.py --single_gpu  --config configs/projects/vid2vid/cityscapes/ampO1.yaml  --output_dir projects/vid2vid/output/cityscapes

ERROR: 
cudnn benchmark: True
cudnn deterministic: False
Creating metadata
Data file extensions: {'seg_maps': 'png', 'images': 'png'}
Searching in dir: seg_maps
Found 1 sequences
Found 30 files
Folder at projects/vid2vid/test_data/cityscapes\seg_maps opened.
Folder at projects/vid2vid/test_data/cityscapes\images opened.
Num datasets: 1
Num sequences: 1
Max sequence length: 30
Epoch length: 1
Concatenate images:
    ext: png
    num_channels: 3
    interpolator: BILINEAR
    normalize: True for input.
Concatenate seg_maps:
    ext: png
    num_channels: 35
    interpolator: NEAREST
    normalize: False for input.
        Num. of channels in the input label: 35
Concatenate images:
    ext: png
    num_channels: 3
    interpolator: BILINEAR
    normalize: True for input.
        Num. of channels in the input image: 3
Concatenate images:
    ext: png
    num_channels: 3
    interpolator: BILINEAR
    normalize: True for input.
        Num. of channels in the input image: 3
Concatenate images:
    ext: png
    num_channels: 3
    interpolator: BILINEAR
    normalize: True for input.
Concatenate seg_maps:
    ext: png
    num_channels: 35
    interpolator: NEAREST
    normalize: False for input.
        Num. of channels in the input label: 35
Concatenate images:
    ext: png
    num_channels: 3
    interpolator: BILINEAR
    normalize: True for input.
        Num. of channels in the input image: 3
Concatenate images:
    ext: png
    num_channels: 3
    interpolator: BILINEAR
    normalize: True for input.
        Num. of channels in the input image: 3
Concatenate images:
    ext: png
    num_channels: 3
    interpolator: BILINEAR
    normalize: True for input.
Concatenate seg_maps:
    ext: png
    num_channels: 35
    interpolator: NEAREST
    normalize: False for input.
        Num. of channels in the input label: 35
Concatenate images:
    ext: png
    num_channels: 3
    interpolator: BILINEAR
    normalize: True for input.
        Num. of channels in the input image: 3
Initialize net_G and net_D weights using type: xavier gain: 0.02
net_G parameter count: 346,972,262
net_D parameter count: 5,597,826
Traceback (most recent call last):
  File "inference.py", line 91, in <module>
    main()
  File "inference.py", line 64, in main
    get_model_optimizer_and_scheduler(cfg, seed=args.seed)
  File "C:\Users\Simon\v2v\imaginaire\imaginaire\utils\trainer.py", line 115, in get_model_optimizer_and_scheduler
    opt_G = get_optimizer(cfg.gen_opt, net_G)
  File "C:\Users\Simon\v2v\imaginaire\imaginaire\utils\trainer.py", line 257, in get_optimizer
    return get_optimizer_for_params(cfg_opt, params)
  File "C:\Users\Simon\v2v\imaginaire\imaginaire\utils\trainer.py", line 276, in get_optimizer_for_params
    betas=(cfg_opt.adam_beta1, cfg_opt.adam_beta2))
  File "C:\Users\Simon\anaconda3\lib\site-packages\apex-0.1-py3.7.egg\apex\optimizers\fused_adam.py", line 79, in __init__
    raise RuntimeError('apex.optimizers.FusedAdam requires cuda extensions')
**RuntimeError: apex.optimizers.FusedAdam requires cuda extensions**

Can you help to fix the issue? 

Many thanks in advance,
Simon

**Comment by simon-eda** [comment]
I foud solution in previous issues:

Hi, I just run fs_vid2vid inferring successfully. I met the same error as you did on Win10, here is my solution:
Change the config file, adding fused_opt: False here:
**\configs\projects\vid2vid\cityscapes\ampO1.yaml**


# Optimization option.
gen_opt:
    type: adam
    **fused_opt: False**
    ......
dis_opt:
    type: adam
    **fused_opt: False**
    ......
