### ISSUE TITLE
AttributeError: module 'torch.distributed' has no attribute 'is_initialized' for fs_vid2vid

### ISSUE THREAD

**Issue by dikshantjn** [NVlabs/imaginaire#93]
I use a windows 10
I am trying to train in a custom data set using this command

python -m torch.distributed.launch --nproc_per_node=8 train.py --config  configs/projects/fs_vid2vid/YouTubeDancing/ampO1.yaml

, gives me the following error

Traceback (most recent call last):
  File "train.py", line 93, in <module>
    main()
  File "train.py", line 56, in main
    train_data_loader, val_data_loader = get_train_and_val_dataloader(cfg)
  File "C:\Users\student\Downloads\imaginaire-master\imaginaire-master\imaginaire\utils\dataset.py", line 75, in get_train_and_val_dataloader
    train_data_loader = _get_data_loader(
  File "C:\Users\student\Downloads\imaginaire-master\imaginaire-master\imaginaire\utils\dataset.py", line 46, in _get_data_loader
    not_distributed = not_distributed or not dist.is_initialized()
AttributeError: module 'torch.distributed' has no attribute 'is_initialized'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\distributed\launch.py", line 263, in <module>
    main()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\distributed\launch.py", line 258, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['C:\\ProgramData\\Anaconda3\\python.exe', '-u', 'train.py', '--local_rank=7', '--config', 'configs/projects/fs_vid2vid/YouTubeDancing/ampO1.yaml']' returned non-zero exit status 1.

**Comment by arunmallya** [comment]
Please see this: https://github.com/pytorch/pytorch/issues/42095
Seems like distributed is still not fully supported on Windows.
