### ISSUE TITLE
RuntimeError: apex.optimizers.FusedAdam requires cuda extensions

### ISSUE THREAD

**Issue by life97** [NVlabs/imaginaire#96]
The environment has been configured according to the installation guide, but when training the MUNIT model, an error is reported:
Initialize net_G and net_D weights using type: orthogonal gain: 1
net_G parameter count: 30,258,966
net_D parameter count: 32,322,498
Traceback (most recent call last):
  File "H:\19xyy\project\imaginaire-master\train.py", line 100, in <module>
    main()
  File "H:\19xyy\project\imaginaire-master\train.py", line 60, in main
    get_model_optimizer_and_scheduler(cfg, seed=args.seed)
  File "H:\19xyy\project\imaginaire-master\imaginaire\utils\trainer.py", line 115, in get_model_optimizer_and_scheduler
    opt_G = get_optimizer(cfg.gen_opt, net_G)
  File "H:\19xyy\project\imaginaire-master\imaginaire\utils\trainer.py", line 257, in get_optimizer
    return get_optimizer_for_params(cfg_opt, params)
  File "H:\19xyy\project\imaginaire-master\imaginaire\utils\trainer.py", line 274, in get_optimizer_for_params
    opt = FusedAdam(params,
  File "G:\Anaconda3\envs\xyy_imagenaire\lib\site-packages\apex\optimizers\fused_adam.py", line 80, in __init__
    raise RuntimeError('apex.optimizers.FusedAdam requires cuda extensions')
RuntimeError: apex.optimizers.FusedAdam requires cuda extensions

I also checked apex, and it is indeed installed. I don’t know why the error was reported. Can I help solve this problem if I ask? Many thanks!

**Comment by life97** [comment]
The versions of nvcc -V and print(torch.version.cuda) are the same. I don’t know why this error is reported. Are there any good suggestions to make the code run correctly? 
![161](https://user-images.githubusercontent.com/56705432/137581221-6d409541-a497-4ab2-9f65-e3ba3882b644.jpg)
![162](https://user-images.githubusercontent.com/56705432/137581222-b2c58a60-1bd0-46fc-bddd-3db72c57e412.jpg)

Looking forward to your reply, thank you very much!
